### ISSUE TITLE
Makefile should match dcloadip

### ISSUE THREAD

**Issue by andressbarajas** [sizious/dcload-serial#1]
Referring to this commit by Protofall:
https://github.com/sizious/dcload-ip/commit/a532c16c8d252f839025253c5fb8977c50aa6723

He makes changes to the target-src/1st_read.bin/Makefile that also scrambles the binary for you! Which is nice!

I think every time we see a 1st_read.bin we should expect it be scrambled.

I just copy and pasted the Makefile from dcload-ip/target-src/1st_read directory to dcload-serial/target-src/1st_read and things worked as I used them.

However I also see that we scramble the 1st_read.bin when we use make-cd(personally I dont use it). Does scrambling an already scrambled binary mess it up?

Either way I think things should match between dcload-ip and dcload-serial when it comes to the files that are generated from the source.

There is probably other stuff in that Protofall commit that should also be ported to dcload-serial.

**Comment by mrneo240** [comment]
Scrambling 3 times results in unscrambled

**Comment by andressbarajas** [comment]
I never knew that.  Thats really cool.

**Comment by sizious** [comment]
You are right, Protofall made some interesting changes in dcload-ip and we should make the same for serial!

**Comment by mrneo240** [comment]
PR here https://github.com/sizious/dcload-serial/pull/2

**Comment by sizious** [comment]
PR merged! Thanks @mrneo240!
