### ISSUE TITLE
Please fix the make-cd makefile!!

### ISSUE THREAD

**Issue by ghost** [sizious/dcload-serial#5]
https://github.com/sizious/dcload-serial/blob/master/make-cd/Makefile#L25

$(SCRAMBLE) needs to be $(CP) otherwise you’re scrambling 1st_read.bin twice. This has already been addressed and fixed in dcload-ip, but has not been fixed here.

**Comment by sizious** [comment]
This has been fixed by @andressbarajas and now merged in this repository.
Please note, this repo contains the 1.0.6 version which is at this time the most advanced dcload-serial version; but it's unofficial.
